---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    # My global config
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanagers:9093

    rule_files:
      # - "rules.yml"

    scrape_config:
      - job_name: 'Prometheus'
        static_configs:
        - targets: ['localhost:9090']